name: Quanta PHP Module builder

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '**'
    types:
      - opened
      - edited
      - synchronize
      - labeled

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  PACKER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:

  build_php_module:
    if: github.event_name == 'push' || contains(github.event.pull_request.labels.*.name, 'release')
    environment: build
    name: 'QM3K PHP Module build'
    runs-on: ubuntu-latest

    steps:
    - name: List files
      run: ls -lRa .

    - name: Clone Quanta PHP Module repository
      uses: actions/checkout@v3
      with:
        path: php-module

    - name: Clone Buildozer repository
      uses: actions/checkout@v3
      with:
        ssh-key: ${{ secrets.BUILDOZER_DEPLOY_KEY }}
        repository: quanta-computing/buildozer
        persist-credentials: true
        path: buildozer-repo

    - name: Build the PHP package
      run: |
        cd buildozer-repo
        ./buildozer -t php56-quanta-mon -o debian -v jessie -s /php-module/ -r php56

    - name: List files again
      run: ls -lRa .
