name: Quanta PHP Module builder

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '**'
    types:
      - opened
      - edited
      - synchronize
      - labeled

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  PACKER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  debian-builds:
    if: github.event_name == 'push' || contains(github.event.pull_request.labels.*.name, 'release')
    environment: build
    name: 'PHP 7.3, 7.4 for debian jessie, stretch, buster'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [php73, php74] #php72, php80, php81, php82
        debian-version: [jessie, stretch, buster] #bullseye, bookworm

    steps:
    - name: Clone Quanta PHP Module repository
      uses: actions/checkout@v3
      with:
        path: php-module

    - name: Clone Buildozer repository
      uses: actions/checkout@v3
      with:
        ssh-key: ${{ secrets.BUILDOZER_DEPLOY_KEY }}
        repository: quanta-computing/buildozer
        persist-credentials: true
        path: tools

    - name: Build the PHP package
      run: |
        cd tools
        ./buildozer -t ${{ matrix.php-version }}-quanta-mon -o debian -v ${{ matrix.debian-version }} -s ../php-module/extension/ -r debian-${{ matrix.debian-version }}
